import { AuthProvider } from "../components/auth/authContext";
import type { Metadata } from "next";
import "./globals.css";
import Header from "./header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout(
  { children, }: Readonly<{ children: React.ReactNode; }>
) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="antialiased">
          <Header/>
          <main>{children}</main>
        </body>
      </AuthProvider>
    </html>
  );
}
